name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck ruby-full
          sudo gem install bashcov -N

      - name: Run tests
        run: ./test.sh
